version: '3'

services:
  jobs:

    build:
      context: .
      dockerfile: Dockerfile

    ports:
    - "5001:5000"
    #volumes:
    #  - ../jobs:/opt/jobs
    #  - ../files:/opt/files
    links:
      - mongo

    depends_on:
      mongo:
        condition: service_healthy

    entrypoint: ["/opt/jobs/pipeline.sh"]

  mongo:

    build: 
      context: .
      dockerfile: Dockerfile.mongo
    user: root
    restart: always
    ports:
      - 27017:27017
    #volumes:
      ##- ../data:/data
      ##- ../files:/files
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep -q 27017"]
    #command: supervisord -n && apt-get update && apt-get install -y csvtool
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: aclaraujo
    #  MONGO_INITDB_ROOT_PASSWORD: ascii

  mongo-express:

    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    links:
      - mongo

    #depends_on:
    #  mongo:
    #    condition: service_healthy

    #environment:
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: stone
